*** markdown to numpy beginning***

In [1]:
import numpy as np

In [2]:
myArr= np.array([[3,6,37,7]], np.int8)


In [3]:
myArr

array([[ 3,  6, 37,  7]], dtype=int8)

In [4]:
myArr[0, 1]

6

In [5]:
myArr.shape


(1, 4)

In [6]:
myArr.dtype


dtype('int8')

In [7]:
myArr[0,2]=45

In [8]:
myArr


array([[ 3,  6, 45,  7]], dtype=int8)

#Array creation: Conversion from other python structure

In [9]:
listarray = np.array([[1,2,3] , [5,8,5] , [0,3,1]] )

In [10]:
listarray


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype


dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
listarray[2,1]=100

In [15]:
listarray


array([[  1,   2,   3],
       [  5,   8,   5],
       [  0, 100,   1]])

In [16]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [17]:
zeros=np.zeros((2,5))

In [18]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
rng=np.arange(15)

In [20]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace=np.linspace(2,5,4)

In [22]:
lspace


array([2., 3., 4., 5.])

In [23]:
emp=np.empty((2,3))

In [24]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
rng=np.arange(99)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
rng.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
rnge=rng.reshape(3,33)


In [30]:
rnge

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
rnge.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
zeros=np.zeros([2,3])

In [33]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
ar=np.array([[1,2,3] , [5,8,5] , [0,3,1]] )

In [35]:
ar.sum(axis=0)

array([ 6, 13,  9])

In [36]:
ar.sum(axis=1)

array([ 6, 18,  4])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
5
8
5
0
3
1


In [39]:
ar.nbytes

36

In [40]:
one=np.array([1,4,3,1213,2])

In [41]:
one.argmax()

3

In [42]:
one.argmin()

0

In [43]:
one.argsort()

array([0, 4, 2, 1, 3], dtype=int32)

In [44]:
ar


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [45]:
ar.argmin()

6

In [46]:
ar.argmax

<function ndarray.argmax>

In [47]:
ar.argmax()

4

In [48]:
ar.argmax(axis=0)

array([1, 1, 1], dtype=int32)

In [49]:
ar.argmax(axis=1)

array([2, 1, 1], dtype=int32)

In [50]:
ar.argmin(axis=0)

array([2, 0, 2], dtype=int32)

In [51]:
ar,argmin(axis=1)

NameError: name 'argmin' is not defined

In [52]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int32)

In [53]:
ar.argsort(axis=0)

array([[2, 0, 2],
       [0, 2, 0],
       [1, 1, 1]], dtype=int32)

In [54]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [63]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 2, 1],
       [0, 2, 1]], dtype=int32)

In [64]:
ar1=np.array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [65]:
ar+ar1

array([[ 2,  4,  6],
       [10, 16, 10],
       [ 0,  6,  2]])

In [66]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [67]:
ar1

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [68]:
ar2=np.array([[0, 1, 2],
       [0, 2, 1],
       [0, 2, 1]])

In [69]:
ar+ar2

array([[ 1,  3,  5],
       [ 5, 10,  6],
       [ 0,  5,  2]])

In [70]:
ar

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [71]:
ar2

array([[0, 1, 2],
       [0, 2, 1],
       [0, 2, 1]])

In [72]:
ar*ar2

array([[ 0,  2,  6],
       [ 0, 16,  5],
       [ 0,  6,  1]])

In [73]:
ar.where(ar>4)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [74]:
np.where(ar>4)

(array([1, 1, 1], dtype=int32), array([0, 1, 2], dtype=int32))

In [75]:
ar.where(ar>5)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [76]:
np.where(ar>5)

(array([1], dtype=int32), array([1], dtype=int32))

In [77]:
ar=np.array([[ 1,  3,  5],
       [ 5, 10,  6],
       [ 0,  5,  2]])

In [78]:
np.where(ar>5)

(array([1, 1], dtype=int32), array([1, 2], dtype=int32))